### ISSUE TITLE
Can't build project

### ISSUE THREAD

**Issue by 1Bulgarian** [jahirxtrap/ingotcraft#1]
Hey, I've tried to build your project myself, because I wanted to add the ores for lead, silver and tin, but I have this issue whenever I tried to build the project:
![image](https://github.com/jahirxtrap/ingotcraft/assets/29731197/a2df38fd-92a7-42ff-9fa4-53fd308513a7)

Any idea how to fix it? (I am kinda new to Java/Fabric modding as a whole)

**Comment by jahirxtrap** [comment]
Try to run the "build" or "jar" task of the gradle project

**Comment by 1Bulgarian** [comment]
If you mean to run the project in a fabric client environment, that is working, I am trying to "export"/build the mod so I can't use it my server, etc.

**Comment by jahirxtrap** [comment]
The compiled mod should appear in fabric/build/jar directory

**Comment by 1Bulgarian** [comment]
for some reason, there isnt a /jar folder into the fabric/build directory

**Comment by 1Bulgarian** [comment]
Okay, I manage to find the jar file, it is not where it is supposed to be, but its there and working.
I have another question tho, how can I change the fabric API version without breaking the whole mod? Because when I do change the fabric api version, this is what I get.
![image](https://github.com/jahirxtrap/ingotcraft/assets/29731197/99d09771-4fc8-4072-b994-3c4c99f81aa1)
